language: node_js

node_js:
  - "11"

before_install:
  - cd Frontend

install:
  - npm install

script:
  - npm run build

after_success:
  - cp config.example.json pasteme
  - cd pasteme
  - rm config.json
  - cp -r ../../Backend api
  - cp ../../LICENSE ../../README.md ./
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically build from travis-ci"
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  

branches:
  only:
    - master

notifications:
  email:
    - lucien@lucien.ink
  on_failure: always

env:
  global:
    - GH_REF: github.com/LucienShui/PasteMe.git
    - P_BRANCH: build
