name: Update submodule

on:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  update:
    if: github.repository == 'LucienShui/PasteMe'
    name: Update submodule
    runs-on: ubuntu-latest

    steps:
      - name: Clone and update submodule
        run: |
          git clone https://github.com/${{ github.repository }}.git -b dev PasteMeDev --recursive
          cd PasteMeDev
          git submodule foreach git pull origin master
          git config user.name "Lucien Shui"
          git config user.email "lucien@lucien.ink"
          git add --all
          if ! git commit -m "Sync submodule at `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"; then exit 0; fi
          git push https://"${{ secrets.GITHUB_PASSWORD }}"@"github.com/${{ github.repository }}.git" dev
